= Bitcoin Core Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Bitcoin-Core: https://bitcoincore.org/[Bitcoin Core]
:electrs: https://github.com/romanz/electrs[electrs]
:Electrum: https://electrum.org/[Electrum]
:Tor: https://www.torproject.org/[Tor]

The configuration for running a Bitcoin node, including the {Bitcoin-Core} server, the {Tor} service, and the {electrs} implementation of the {Electrum} wallet.

These are configuration files for my Bitcoin Core pod.
See the https://github.com/jwillikers/home-lab-helm[home-lab-helm] repository for the pod's configuration.

== Usage

The configuration files are organized by service.
The files are meant to be mounted inside their respective containers at the necessary location.
The home-lab-helm Kubernetes configuration expects this repository to be in a specific location.
Follow these instructions to put the files in the expected location.

. Create the `~/Projects` directory.
+
[,sh]
----
mkdir --parents ~/Projects
----

. Clone the repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects/ clone https://github.com/jwillikers/bitcoin-core-config
----

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This project is licensed under the https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]
