= Bitcoin Core Config
:experimental:

== Getting Started

[,sh]
----
sudo btrfs subvolume create /home/core
----

[,sh]
----
echo (getent group systemd-journal) | sudo tee -a /etc/group
----

Create a primary user account named `core` for running containers with Podman.
Place this user's home directory in a separate Btrfs subvolume, disable login, and ensure that the user has subuids.
+
--
[,sh]
----
sudo useradd \
  --add-subids-for-system \
  --comment "Primary account for running containers" \
  --create-home \
  --groups systemd-journal \
  --shell /usr/sbin/nologin \
  --system \
  --user-group \
  core
----

The `--root` flag can be used to create this user in the given chroot environment.

[NOTE]
----
You may want to set the UID explicitly, especially when using shared NFS volumes which require the same UID across different machines.
Use the `--uid` option to set this explicitly.
----
--

. If for some reason, you still need subuid and subgid ranges for the user, follow these steps.

.. Calculate the first value for the next subuid allotment.
+
--
If `/etc/subuid` is empty, use 100,000 as the initial value.

[,sh]
----
set new_subuid 100000
----

Otherwise, use the following function to calculate the next available subuid range.

[,sh]
----
set new_subuid (math (tail -1 /etc/subuid | awk -F ":" '{print $2}') + 65536)
----
--

.. Calculate the first value for the next subuid allotment.
+
--
If `/etc/subgid` is empty, use 100,000 as the initial value.

[,sh]
----
set new_subgid 100000
----

Otherwise, use the following function to calculate the next available subgid range.

[,sh]
----
set new_subgid (math (tail -1 /etc/subgid | awk -F ":" '{print $2}') + 65536)
----
--
 
.. Configure the `core` user with the necessary subuid and subgid ranges.
+
[,sh]
----
sudo usermod \
  --add-subuids $new_subuid-(math $new_subuid + 65535) \
  --add-subgids $new_subgid-(math $new_subgid + 65535) \
  core
----

. Allow running the user's systemd services when the user is not logged in. 
This also ensures that the user's runtime directory is available.
+
[,sh]
----
sudo loginctl enable-linger core
----

. Open a shell as the `core` user with the following command.
+
[,sh]
----
sudo -H -u core fish -c 'cd; fish'
----

. Configure the `XDG_RUNTIME_DIR` environment variable for the user in order for sockets to be found correctly.
+
[,sh]
----
set -Ux XDG_RUNTIME_DIR /run/user/(id -u)
----

. If you want to get automatic updates, make sure to enable Podman's automatic update timer for the user.
+
[,sh]
----
systemctl --user enable --now podman-auto-update.timer
----

[,sh]
----
mkdir -p ~/.config/containers/systemd
----

.~/.config/containers/systemd/podman.network
[,systemd]
----
[Network]
IPv6=yes
----

[,sh]
----
systemctl --user daemon-reload
----

[,sh]
----
mkdir -p ~/Projects ~/container-volumes/bitcoin-core-server-data ~/container-volumes/electrs-data
----

. If desired, mount a separate disk to `~/container-volumes`, as Bitcoin Core is going to be using a lot of disk space
+
.. Add an entry to mount the volume to `~/container-volumes`.
+
./etc/fstab
[,fstab]
----
UUID=f43665b0-2150-4165-97c3-71159544422c /var/home/core/container-volumes btrfs subvol=bitcoin,noatime,autodefrag,commit=120,compress=zstd:1,x-systemd.device-timeout=0 0 0
----

.. Double check there are no errors in `/etc/fstab`.
+
[,sh]
----
sudo findmnt --verify --verbose
----

.. Reload systemd.
+
[,sh]
----
sudo systemctl daemon-reload
----

.. Mount the filesystem as defined in fstab.
+
[,sh]
----
sudo mount -a
----

.. Set the correct ownership for the volume.
+
[,sh]
----
sudo chown -R core:core /var/home/core/container-volumes
----

[,sh]
----
git -C ~/Projects/ clone https://github.com/jwillikers/bitcoin-core-config
----

[,sh]
----
cd ~/Projects/bitcoin-core-config
----

mkdir -p ~/container-volumes/bitcoin-core-tor-run/
chmod 0700 ~/container-volumes/bitcoin-core-tor-run/

. First, create the Bitcoin pod which will run Bitcoin Core server container, the Tor container, and the electrs container.
+
[,sh]
----
podman pod create \
  --name bitcoin-core \
  --network podman \
  --replace \
  --userns keep-id
----

[,sh]
----
podman run \
  --detach \
  --label "io.containers.autoupdate=registry" \
  --name bitcoin-core-tor \
  --pod bitcoin-core \
  --rm \
  --user (id -u):(id -g) \
  --volume ~/Projects/bitcoin-core-config/tor:/etc/tor:ro,Z \
  docker.io/osminogin/tor-simple:latest
----

[,sh]
----
podman run \
  --detach \
  --label "io.containers.autoupdate=registry" \
  --name bitcoin-core-server \
  --pod bitcoin-core \
  --requires bitcoin-core-tor \
  --rm \
  --user (id -u):(id -g) \
  --volume ~/container-volumes/bitcoin-core-server-data:/.bitcoin:z \
  --volume ~/Projects/bitcoin-core-config/bitcoin/bitcoin.conf:/.bitcoin/bitcoin.conf:ro,Z \
  --volume ~/Projects/bitcoin-core-config/bitcoin/bitcoin.conf.d:/.bitcoin/bitcoin.conf.d:ro,Z \
  docker.io/lncm/bitcoind:v25.1
----

[,sh]
----
git -C ~/Projects/ clone https://github.com/romanz/electrs
----

[,sh]
----
cd ~/Projects/electrs
----

[,sh]
----
git switch -c v0.10.0 v0.10.0
----

[,sh]
----
podman build -t electrs-app .
----

// todo Try using getumbrel/electrs instead

[,sh]
----
podman run \
    --detach \
    --label "io.containers.autoupdate=registry" \
    --name electrs \
    --pod bitcoin-core \
    --requires bitcoin-core-server \
    --rm \
    --user (id -u):(id -g) \
    --volume ~/container-volumes/bitcoin-core-server-data:/data/.bitcoin:ro,z \
    --volume ~/container-volumes/electrs-data:/data/db:Z \
    --volume ~/Projects/bitcoin-core-config/electrs/config.toml:/etc/electrs/config.toml:ro,Z \
    docker.io/getumbrel/electrs:v0.9.14
----
